### ISSUE TITLE
Minor Issue on first test. Different output from video.

### ISSUE THREAD

**Issue by piercemcgeough** [nothingworksinc/ticketbeast#22]
I am not getting any red colours on my first test and it output is different from the video.
I noticed my phpunit is 5.7.5

```
PHPUnit 5.7.5 by Sebastian Bergmann and contributors.

.
Fatal error: Class 'Concert' not found in /Users/piercemcgeough/development/tutorials/ticketbeast/tests/features/ViewConcertListingTest.php on line 15

Fatal error: Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable.' in /Users/piercemcgeough/development/tutorials/ticketbeast/vendor/laravel/framework/src/Illuminate/Container/Container.php:763
Stack trace:
#0 /Users/piercemcgeough/development/tutorials/ticketbeast/vendor/laravel/framework/src/Illuminate/Container/Container.php(644): Illuminate\Container\Container->build('Illuminate\\Cont...', Array)
#1 /Users/piercemcgeough/development/tutorials/ticketbeast/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#2 /Users/piercemcgeough/development/tutorials/ticketbeast/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(154): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#3 /Users/piercemcgeough/development/tutorials/ticketbeast/vendor/laravel/framework/src/Illuminate/Foundation/ in /Users/piercemcgeough/development/tutorials/ticketbeast/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 763
```

**Comment by adamwathan** [comment]
Hey Pierce, can you share the code in your test? It sounds like you are missing a `use App\Concert;` at the top of the file.

The exception handler error is more surprising to me; can you try cloning the repository and checking out the corresponding commit for the lesson you are on and seeing if the errors go away?

**Comment by piercemcgeough** [comment]
Aww balls I see what it is now. I had kept my example test file. It works after removing that.
What do you use for sublime text code completion and moving through functions etc.

Thanks
